### ISSUE TITLE
Multiples vulnerabilites

### ISSUE THREAD

**Issue by MilesTEG1** [Bleala/Vdirsyncer-DOCKERIZED#10]
Hello,
I found times to retry your docker image :)
But Docker says that there is some vulnerabilities:
![image](https://github.com/Bleala/Vdirsyncer-DOCKERIZED/assets/29298312/92ac68a3-e67a-4772-99d6-b2cc90dd73a3)

Can you update those packages?

Thanks in advance.

**Comment by MilesTEG1** [comment]
Hello again @Bleala 
I managed to limit the CVE vulnerability to only one... 😅 
![image](https://github.com/Bleala/Vdirsyncer-DOCKERIZED/assets/29298312/a35d2fb1-c347-4468-bfeb-5303a5fdb34a)

I deleted my old fork and recreated it with your latest version, and [do some modifications of my own.](https://github.com/MilesTEG1/Vdirsyncer-DOCKERIZED/tree/milesteg1-dev). 
Here a summary:

- Change install method for superconix (get latest binary from github);
- Change `alpine:3.17.3` to `alpine:3.18.2`
- Separate Dockerfile for amd64 and arm64v8 because of the different hash for superconix fils download verification
- Change Python `3.10.11` to `3.11.4`
- `README.md` : Changes in accord of Dockerfiles modifications.
- Fix non-working commands in `README.md`

Will writing this, I see you made some commits 😄

**Comment by MilesTEG1** [comment]
I also "variabilized" some path, like python-3.11.
Have a look at what I changed ☺️

**Comment by Bleala** [comment]
Hello there!

I already updatet to alpine 3.18.2 and included some of your fixes/improvements. 😄 

I will fix the supercronic and multiple dockerfile issue next week or so, I need multiple dockerfiles anyway, because I want to do automatic docker builds and need multiple dockerfiles.

Greetings

**Comment by MilesTEG1** [comment]
Hi again,
Thanks for applying some of my fixes/improvements 😃 

With the last changes, will we be able to launch this:
```shell
docker exec -it vdirsyncer vdirsyncer discover
```
Because I got this:
![image](https://github.com/Bleala/Vdirsyncer-DOCKERIZED/assets/29298312/7e996ff0-c357-4427-9975-0d0b410869bc)

By the way, there is an error in the Readme:
![image](https://github.com/Bleala/Vdirsyncer-DOCKERIZED/assets/29298312/0cd8143a-e166-4e19-9ba9-13211cd7bef8)

**Comment by Bleala** [comment]
Hey,

did you re-pull the image?
I uploaded the `vdirsyncer` global command fix with the same tag as the image before.

For me the `vdirsyncer discover` is working:
![2023-06-23 15_11_10-WSL-Ubuntu](https://github.com/Bleala/Vdirsyncer-DOCKERIZED/assets/51357182/a7245279-ab82-4e55-b374-e7ad42f82d54)

Also the container is running normally:
![grafik](https://github.com/Bleala/Vdirsyncer-DOCKERIZED/assets/51357182/b392d709-7774-4273-b2d1-3d023a73d051)

Commands in README.md are fixed.

Greetings

**Comment by MilesTEG1** [comment]
> did you re-pull the image?
> I uploaded the `vdirsyncer` global command fix with the same tag as the image before.

Oh my, I think I pull to early the image.
I'll retry ;)
Verdict: you did great 👍🏻 
![image](https://github.com/Bleala/Vdirsyncer-DOCKERIZED/assets/29298312/88b4c353-c4e7-40b2-9c77-f9be2df87a83)
Thanks !

**Comment by MilesTEG1** [comment]
> I will fix the supercronic and multiple dockerfile issue next week or so, I need multiple dockerfiles anyway, because I want to do automatic docker builds.

For that, I wonder how you'll achieve the auto build... I don't know how to do it...
