### ISSUE TITLE
Container shutdown timeout of 10s

### ISSUE THREAD

**Issue by GosuJunk** [Bleala/Vdirsyncer-DOCKERIZED#21]
Hi Bleala, and thank you for the work you put on vdirsyncer it's been very useful !!

I noticed a fixed 10s timeout when turning down a container. It's not really an issue but it becomes a nuisance when testing with multiple containers, because turning down 10x in a row means 100 seconds ! I was wondering where this was set and whether I could modify it. I can force the shutdown with docker compose stop -t , but I would prefer to understand why there is a timeout in the first place.

Thanks !

**Comment by Bleala** [comment]
Hello!

The timeout seems to come from the Dockerfile healthcheck:

```
# Healthcheck
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=1 \
  CMD ps -ef | grep -e "supercronic" | grep -v -e "grep" || exit 1
```

You could remove the `--timeout=10s` option and check if this solves your problem.

I do not restart the container very often so I never noticed this problem.

Hope this helps you!

Greetings
