### ISSUE TITLE
When restarting container, additional crontab line is added

### ISSUE THREAD

**Issue by jeepeegit** [Bleala/Vdirsyncer-DOCKERIZED#29]
When restarting container, additional crontab line is added.

Every time I restart the container an extra crontab line is added.  And then executed x times instead of 1 x.

container restarted 2 x and then it says this in the /etc/crontab/vdirsyncer

docker exec -it vdirsyncer /bin/sh -c “cat /etc/crontabs/vdirsyncer”
0/5 * * * * * * /usr/local/bin/vdirsyncer -c /vdirsyncer/config/google_nc.ini metasync && /usr/local/bin/vdirsyncer -c /vdirsyncer/config/google_nc.ini sync
0/5 * * * * * * /usr/local/bin/vdirsyncer -c /vdirsyncer/config/google_nc.ini metasync && /usr/local/bin/vdirsyncer -c /vdirsyncer/config/google_nc.ini sync
0/5 * * * * * * /usr/local/bin/vdirsyncer -c /vdirsyncer/config/google_nc.ini metasync && /usr/local/bin/vdirsyncer -c /vdirsyncer/config/google_nc.ini sync

    environment:
      - TZ=Europe/Amsterdam
      - VDIRSYNCER_CONFIG=/vdirsyncer/config/google_nc.ini
      - AUTOUPDATE=false # set to true for automatic Vdirsyncer and dependencies updates on container startup, default to false
      - AUTODISCOVER=false # default false
      - CRON_TIME=0/5 * * * * *
      - AUTOSYNC=true
      - LOG=/vdirsyncer/vdirsyncer.log

**Comment by Bleala** [comment]
Hello @jeepeegit 

Your issue should be fixed by the following PR: #31 

The new container is currently building and should be available soon with the new release 2.5.5

Greetings
