### ISSUE TITLE
CRON_TIME has no default as suggested by readme

### ISSUE THREAD

**Issue by lonesomewalker** [Bleala/Vdirsyncer-DOCKERIZED#35]
just try it yourself, leave it empty -> an error occurs, says the cron is broken.

**Comment by Bleala** [comment]
I can't confirm that, I started a new container where I only set `AUTOSYNC` to `true` for test and this is the result:

```
/vdirsyncer $ cat /etc/crontabs/vdirsyncer
*/15 * * * * /usr/local/bin/vdirsyncer -c /vdirsyncer/config metasync     && /usr/local/bin/vdirsyncer -c /vdirsyncer/config sync 
/vdirsyncer $ echo "${CRON_TIME}"
*/15 * * * *
```

If you set the `CRON_TIME` like that `CRON_TIME=`, then you overwrite the default value with nothing, so then `CRON_TIME` would be empty.

**Comment by lonesomewalker** [comment]
Maybe you don't know what DEFAULT means, but where i am coming from means: if nothing is altered from default file.
So, yes, CRON_TIME is written as in the docker-compose.yml.

Means: either it is a REAL default (which is not) or enter default value there.
I don't care because i can understand how it works, but for other people which are not tech savy... saves them some lifetime and also the statement that it does not work ;-)

So MAYBE you should comment CRON_TIME out...?
