### ISSUE TITLE
Update vdirsyncer to latest version : 0.19.1

### ISSUE THREAD

**Issue by MilesTEG1** [Bleala/Vdirsyncer-DOCKERIZED#6]
Hello,
I want to use the last version of vdirsyncer, the 0.19.1.
Can you update your image to have this new version ?
Or add something to let the app update itself after a container restart ?

Thanks in advance.

**Comment by MilesTEG1** [comment]
@Bleala Hello,
You made a wonderful job in creating this`Vdirsyncer-DOCKERIZED`.
But it's not up to date now. And some vulnerabilities are present, some critical.
![image](https://user-images.githubusercontent.com/29298312/230744122-54059866-9cf6-4b95-8574-2c9ac39f0797.png)

With Docker Desktop, I saw the dev image you made, and still there is some vulnerabilities...
![image](https://user-images.githubusercontent.com/29298312/230744181-a7f98cbe-1d22-4116-a53e-94b35568e28b.png)


I'm not a professional developer, and not much in docker.
I can learn from examples, but I'm a novice in that.
But I tried something, using your work. I forked your repository, and try to learn how to update all the things that needs to be updated:
- alpine image with using a python3-alpine image to have all we need: python & pip
- Vdirsyncer (for this one, I had to find a way to install pipx as a user to avoid a warning, and your `Dockerfile` was well commented, so I found a way to do it.

I also add a command in the `start.sh` script in order to update Vdirsyncer at startup, if there is an update, so by restarting the container, Vdirsyncer will be auto updated.

![image](https://user-images.githubusercontent.com/29298312/230745756-3aea8321-9d31-40b2-b437-4f1059d19ebd.png)

![image](https://user-images.githubusercontent.com/29298312/230745702-f5c8856f-cff3-416c-a405-23671eee893f.png)

It's working fine, after several tries. :satisfied:
In learning how to do that, I learned many new things 😄 

All those modifications are in the dev branch on my fork: https://github.com/MilesTEG1/Vdirsyncer-DOCKERIZED/tree/dev

Do you agree for me to do a pull request with my modifications?
As I said, I'm not a professional developer, so making all architectures images and publishing them in GitHub registry or Docker Hub aren't in my capabilities... I don't know how to do that.

I hope you'll answer this message and agreed.
And maybe, you'll want to explain to me how to made multiple OS / Arch versions...
(At the moment, I use my Macbook Air M2, so I assume my image is ARM64).

Thanks for reading.

**Comment by Bleala** [comment]
@MilesTEG1 
Hello there!
I'm already working on the 19.1 update and I'm also doing a little bit of rewrite of my Dockerfile.

Also i thought about the auto update function, but I don't know if this would be the best way, because same dependencies change with every Vdirsyncer version.

I'll upload the updated version today and also look at your changes in your repository. After I updated Dockerfile you can compare again and create a pull request with your modifications if you want to.

Greetings 😄

**Comment by MilesTEG1** [comment]
Hello @Bleala 
Thanks for your update :)

> Also i thought about the auto update function, but I don't know if this would be the best way, because same dependencies change with every Vdirsyncer version.

You may be right on this 😀 
In my fork, I was trying to use pipx to install and update vdirscyncer, but I got some troubles to achieve it as I'm lacking skills in programming 😅 

Question for you, as I see your new Dockerfile:
Have you tried to use `python:3-alpine` instead of `alpine` base image?
And, isn't it preferable to use `FROM alpine` instead of specifying a version `FROM alpine:3.17.3`? We can get the latest version of the image.

I'll try to build an image with `python:3-alpine` with all of your changes when I get some time ^^

And I'll try to get the autoupdate working ;)

Greetings too 😄

**Comment by MilesTEG1** [comment]
@Bleala 
Yeah! Great job!
I'll try this new image :) and I think I'll love it.
Your choice to set an environment variable `AUTOUPDATE` is an excellent choice! Well done.



> Yeah i tried to use the `python:3-alpine` base image, but I like the `alpine` one more, because I want to add everything by myself.

I may have the same opinion on some other things, but sometimes, I prefer an already done things 😀 But, in this case, you may be right again. Controlling what you put in the final image is a better choice, I think.



> And I also used `FROM alpine:3.17.3`, because I can guarantee that everything is working and it is the latest official release of the alpine image anyway right now.
> Maybe I'll also add a automatic base image update feature.
You're right too here, but this part is only for building the image, that's not for everyone to do 😀 I had learned some things trying to build an updated image, but I failed to achieve all I wanted to do.
I think setting something, like an environnement variable to modify, to get the latest image when you build your image is a desirable choice, because you'll test this image 😉 

Thanks for your replies and for your time 😃

**Comment by MilesTEG1** [comment]
@Bleala 
Yeah! Great job!
I'll try this new image :) and I think I'll love it.
Your choice to set an environment variable `AUTOUPDATE` is an excellent choice! Well done.



> Yeah i tried to use the `python:3-alpine` base image, but I like the `alpine` one more, because I want to add everything by myself.

I may have the same opinion on some other things, but sometimes, I prefer an already done things 😀 But, in this case, you may be right again. Controlling what you put in the final image is a better choice, I think.



> And I also used `FROM alpine:3.17.3`, because I can guarantee that everything is working and it is the latest official release of the alpine image anyway right now.
> Maybe I'll also add a automatic base image update feature.
You're right too here, but this part is only for building the image, that's not for everyone to do 😀 I had learned some things trying to build an updated image, but I failed to achieve all I wanted to do.
I think setting something, like an environnement variable to modify, to get the latest image when you build your image is a good choice, because you'll test this image 😉

**Comment by Bleala** [comment]
I'll close this issue, the autoupdate feature is working as expected. 😄
