### ISSUE TITLE
crond: root: Permission denied

### ISSUE THREAD

**Issue by Benni-chan** [Bleala/Vdirsyncer-DOCKERIZED#7]
since the last updates I get this error message and no syncing

[[2023-05-05 12:21:26]] crond: crond (busybox 1.35.0) started, log level 8
[[2023-05-05 12:21:26]] crond: root: Permission denied
[[2023-05-05 12:22:00]] crond: root: Permission denied

i already reset my config directory so the permissions are correct on all files.

**Comment by Bleala** [comment]
Hello,

thanks for your hint, I'm already looking for a solution, got the same error.

Will update the container as soon as I can.

Greetings
