### ISSUE TITLE
Impossible to login to any Google services from cli

### ISSUE THREAD

**Issue by thiphariel** [Bleala/Vdirsyncer-DOCKERIZED#8]
Hi,

It's confirmed that with the 0.19 update, it's no longer possible to use that fix : https://github.com/pimutils/vdirsyncer/issues/975#issuecomment-1275698939

The cli doesn't ask for the code to paste in the ssh session.

Is there a way to handle that on your side or it's only a fix vdirsyncer can do?

Thank you!

**Comment by Bleala** [comment]
Hey @thiphariel 

I'm sorry, this is something I cannot fix, this is clearly a vdirsyncer bug. 😢 

Maybe this is working for you, seems there is a workaround for this problem: [Issue 1063](https://github.com/pimutils/vdirsyncer/issues/1063)

Hope the Devs of Vdirsyncer are fixing this problem soon.

Greetings

**Comment by thiphariel** [comment]
Hey!

Yeah, I kinda asked just in case you could do something ahah
I ran a vdirsyncer on my local machine and pasted the access token on my server yeah, it now work.

Hope they will find a solution for the 0.19+ version :D

Thank you for the docker setup!
