### ISSUE TITLE
Question about syncing from zimbra to mailcow

### ISSUE THREAD

**Issue by killmasta93** [Bleala/Vdirsyncer-DOCKERIZED#9]
Hi
Currently trying to migrate zimbra contacts and calendars to mailcow, i was looking at the https://github.com/Bleala/Vdirsyncer-DOCKERIZED/blob/main/files/examples/config.example 
but could not find the example of the mailcow 
would it be possible an example?

Thank you

**Comment by Bleala** [comment]
Hello @killmasta93 

a valid mailcow carddav config would be:

```
[storage mailcow]
type = "carddav"
url = "https://mailcow.example.com/SOGo/dav/"
username = "your_username"
password = "your_password"
```

And a caldav example:

```
[storage mailcow_caldav]
type = "caldav"
url = "https://mailcow.example.com/SOGo/dav/"
username = "your_username"
password = "your_password"
```

The version for pairs (carddav) would be:

```
[pair apple_mailcow_carddav]
a = "apple"
b = "mailcow"
collections = [["all", "card", "personal"]]
conflict_resolution = "b wins"
```

Hope this helps

Greetings
